{% set name = "ncdu" %}
{% set version = "1.12" %}
{% set sha256 = "820e4e4747a2a2ec7a2e9f06d2f5a353516362c22496a10a9834f871b877499a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://dev.yorhel.nl/download/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: ./configure --prefix=${PREFIX} && make && make install

requirements:
  build:
    #- conda-forge/toolchain

about:
  home: https://dev.yorhel.nl/ncdu
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'NCurses Disk Usage'

  description: |
    Ncdu is a disk usage analyzer with an ncurses interface. It is designed
    to find space hogs on a remote server where you don't have an entire
    graphical setup available, but it is a useful tool even on regular desktop
    systems. Ncdu aims to be fast, simple and easy to use, and should be able
    to run in any minimal POSIX-like environment with ncurses installed.
  doc_url: https://dev.yorhel.nl/ncdu/man
